In [1]:
import spartan as st

Using backend cpu


In [2]:
import numpy as np
import sparse

# CPU Dense

In [3]:
A = st.DTensor.from_numpy(np.random.rand(3, 4))
print(A)

DTensor(
array([[0.34118167, 0.42776057, 0.66548719, 0.51248589],
       [0.59157547, 0.6512271 , 0.65754365, 0.22235178],
       [0.64277602, 0.86937208, 0.24762643, 0.38732096]])
)


## Get Attributes

In [4]:
print(A.shape)
print(A.dtype)
print(A.T)

(3, 4)
float64
DTensor(
array([[0.34118167, 0.59157547, 0.64277602],
       [0.42776057, 0.6512271 , 0.86937208],
       [0.66548719, 0.65754365, 0.24762643],
       [0.51248589, 0.22235178, 0.38732096]])
)


## Index and Slice

In [5]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

3
DTensor(
array([0.34118167, 0.42776057, 0.66548719, 0.51248589])
)
DTensor(
array([0.42776057, 0.6512271 , 0.86937208])
)
DTensor(
array([[0.34118167, 0.42776057],
       [0.59157547, 0.6512271 ],
       [0.64277602, 0.86937208]])
)


## Reduction operations

In [6]:
print(A.sum())
print(A.sum(axis=0))

6.216708809676708
DTensor(
array([1.57553316, 1.94835975, 1.57065726, 1.12215863])
)


In [7]:
print(st.sum(A))
print(st.sum(A, axis=0))

6.216708809676708
DTensor(
array([1.57553316, 1.94835975, 1.57065726, 1.12215863])
)


## Binary operations

In [8]:
B = st.DTensor.from_numpy(np.random.rand(3, 4))

In [9]:
print(A+B)
print(st.add(A, B))

DTensor(
array([[0.79230258, 0.72923078, 1.47336892, 0.93713784],
       [0.60863963, 1.58634169, 1.47971021, 0.30383823],
       [1.10772118, 1.30430985, 1.01746704, 0.9845281 ]])
)
DTensor(
array([[0.79230258, 0.72923078, 1.47336892, 0.93713784],
       [0.60863963, 1.58634169, 1.47971021, 0.30383823],
       [1.10772118, 1.30430985, 1.01746704, 0.9845281 ]])
)


In [10]:
print(A.dot(B.T))
print(st.dot(A, B.T))

DTensor(
array([[1.03813433, 0.99472909, 1.16305929],
       [1.08883725, 1.17779576, 1.19728728],
       [0.91658896, 1.05908253, 1.09892207]])
)
DTensor(
array([[1.03813433, 0.99472909, 1.16305929],
       [1.08883725, 1.17779576, 1.19728728],
       [0.91658896, 1.05908253, 1.09892207]])
)


# CPU Sparse

In [11]:
A = np.random.rand(3, 4)
A[A<0.8] = 0
A = st.STensor.from_numpy(A)
print(A)
print(A.todense())

STensor(<COO: shape=(3, 4), dtype=float64, nnz=2, fill_value=0.0>)
DTensor(
array([[0.91353755, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.88593596, 0.        , 0.        ]])
)


## Get Attributes

In [12]:
print(A.shape)
print(A.dtype)
print(A.T)

(3, 4)
float64
STensor(<COO: shape=(4, 3), dtype=float64, nnz=2, fill_value=0.0>)


## Index and Slice

In [13]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

3


c:\Users\bailean\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\dispatcher.py:289: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ModuleNotFoundError(No module named 'numba.targets')'.
  entrypoints.init_all()


STensor(<COO: shape=(4,), dtype=float64, nnz=1, fill_value=0.0>)
STensor(<COO: shape=(3,), dtype=float64, nnz=1, fill_value=0.0>)
STensor(<COO: shape=(3, 2), dtype=float64, nnz=2, fill_value=0.0>)


## Reduction operations

In [14]:
print(A.sum())
print(A.sum(axis=0).todense())

1.7994735061707863
DTensor(
array([0.91353755, 0.88593596, 0.        , 0.        ])
)


In [15]:
print(st.sum(A))
print(st.sum(A, axis=0).todense())

1.7994735061707863
DTensor(
array([0.91353755, 0.88593596, 0.        , 0.        ])
)


## Binary operations

In [16]:
B = np.random.rand(3, 4)
B[B<0.8] = 0
B = st.STensor.from_numpy(B)

In [17]:
print(A+B)
print((A+B).todense())
print(st.add(A, B))
print(st.add(A, B).todense())

STensor(<COO: shape=(3, 4), dtype=float64, nnz=6, fill_value=0.0>)
DTensor(
array([[0.91353755, 0.        , 0.91326679, 0.        ],
       [0.        , 0.96693703, 0.89383659, 0.81370615],
       [0.        , 0.88593596, 0.        , 0.        ]])
)
STensor(<COO: shape=(3, 4), dtype=float64, nnz=6, fill_value=0.0>)
DTensor(
array([[0.91353755, 0.        , 0.91326679, 0.        ],
       [0.        , 0.96693703, 0.89383659, 0.81370615],
       [0.        , 0.88593596, 0.        , 0.        ]])
)


In [18]:
print(A.dot(B.T))
print(A.dot(B.T).todense())
print(st.dot(A, B.T))
print(st.dot(A, B.T).todense())

AttributeError: module 'numba' has no attribute 'numpy_support'

# GPU Dense

In [19]:
import sys
sys.path.append('../../')

In [20]:
import spartan as st

st.load_backend('gpu')

Using backend cpu


c:\Users\bailean\AppData\Local\Programs\Python\Python310\lib\site-packages\spartan\backend\__init__.py:62: UserWarning: GPU not available! Use CPU backend instead.
  warnings.warn(msg)


In [ ]:
import torch

In [ ]:
A = st.DTensor(torch.rand(3, 4))

## Attributes

In [ ]:
print(A.shape)
print(A.dtype)
print(A.T)

## Slice

In [ ]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

## Reduction Operations

In [ ]:
print(A.sum())
print(A.sum(axis=0))

In [ ]:
print(st.sum(A))
print(st.sum(A, axis=0))

## Binary Operations

In [ ]:
B = st.DTensor(torch.rand(3, 4))

In [ ]:
print(A+B)
print(st.add(A, B))

In [ ]:
print(A.dot(B.T))
print(st.dot(A, B.T))

## GPU Sparse
**Notice**: Some oeprations are not supported for GPU STensor yet!

In [ ]:
import scipy.sparse as ssp

In [ ]:
A = np.random.rand(3, 4)
A[A<0.8] = 0

In [ ]:
A = np.random.rand(3, 4)
A[A<0.8] = 0
A = st.STensor.from_numpy(A)
print(A)
print(A.todense())

## Attributes

In [ ]:
print(A.shape)
print(A.dtype)
# print(A.T)

## Index and Slice
**Notice**: Pytorch GPU sparse tensor doesn't support complex slice yet!

In [ ]:
print(len(A))
print(A[0])

## Reduction operations

In [ ]:
print(A.sum())
print(A.sum(axis=0).todense())

In [ ]:
# print(st.sum(A))
# print(st.sum(A, axis=0).todense())

## Binary operations

In [ ]:
B = np.random.rand(3, 4)
B[B<0.8] = 0
B = st.STensor.from_numpy(B)

In [ ]:
print(A+B)
print((A+B).todense())
# print(st.add(A, B))
# print(st.add(A, B).todense())